export const NICOSIA = [
  {
    id: 38643,
    name: "VASSILIOU MAKEDONOS RESIDENCE",
    // images: [
    //   ProjectImage1,
    //   ProjectImage2,
    //   ProjectImage3,
    //   ProjectImage4,
    //   ProjectImage5,
    // ],
    pricePerSquare: 14770,
    type: "Жилой дом",
    area: 48,
    floors: 4,
    apartments: 20,
    constructionType: "Монолит",
    features: [
      "Парковка",
      "Детская площадка",
      "Возле школы",
      "Возле детсада",
      "Возле супермаркета",
      "Возле больницы",
    ],
  },
  {
    id: 15834,
    name: "RESIDENCE BIANCO",
    // images: [
    //   ProjectImage1,
    //   ProjectImage2,
    //   ProjectImage3,
    //   ProjectImage4,
    //   ProjectImage5,
    // ],
    pricePerSquare: 14770,
    type: "Жилой дом",
    area: 48,
    floors: 4,
    apartments: 20,
    constructionType: "Монолит",
    features: [
      "Парковка",
      "Детская площадка",
      "Возле школы",
      "Возле детсада",
      "Возле супермаркета",
      "Возле больницы",
    ],
  },
  {
    id: 28647,
    name: "KINNIS GRAND VALLEY RESIDENCE",
    // images: [
    //   ProjectImage1,
    //   ProjectImage2,
    //   ProjectImage3,
    //   ProjectImage4,
    //   ProjectImage5,
    // ],
    pricePerSquare: 14770,
    type: "Жилой дом",
    area: 48,
    floors: 4,
    apartments: 20,
    constructionType: "Монолит",
    features: [
      "Парковка",
      "Детская площадка",
      "Возле школы",
      "Возле детсада",
      "Возле супермаркета",
      "Возле больницы",
    ],
  },
  {
    id: 34664,
    name: "KING PHILIP RESIDENCE",
    // images: [
    //   ProjectImage1,
    //   ProjectImage2,
    //   ProjectImage3,
    //   ProjectImage4,
    //   ProjectImage5,
    // ],
    pricePerSquare: 14770,
    type: "Жилой дом",
    area: 48,
    floors: 4,
    apartments: 20,
    constructionType: "Монолит",
    features: [
      "Парковка",
      "Детская площадка",
      "Возле школы",
      "Возле детсада",
      "Возле супермаркета",
      "Возле больницы",
    ],
  },
  {
    id: 76845,
    name: "CITY TERRACE",
    // images: [
    //   ProjectImage1,
    //   ProjectImage2,
    //   ProjectImage3,
    //   ProjectImage4,
    //   ProjectImage5,
    // ],
    pricePerSquare: 14770,
    type: "Жилой дом",
    area: 48,
    floors: 4,
    apartments: 20,
    constructionType: "Монолит",
    features: [
      "Парковка",
      "Детская площадка",
      "Возле школы",
      "Возле детсада",
      "Возле супермаркета",
      "Возле больницы",
    ],
  },
];
